"""
Adaptive Raising Teacher — Claude-driven conversational prompts.

Instead of static prompt lists, each teacher turn is generated by Claude
based on the conversation so far. The teacher has raising philosophy,
session history, and consolidation feedback in context.

Falls back to simple heuristics if Claude CLI is unavailable.
"""

import json
import random
import shutil
import tempfile
import time
from pathlib import Path
from subprocess import run as subprocess_run
from typing import Dict, List, Optional, Any


def _find_claude_binary() -> str:
    found = shutil.which('claude')
    if found:
        return found
    for candidate in [
        Path.home() / '.local' / 'bin' / 'claude',
        Path('/usr/local/bin/claude'),
        Path.home() / '.npm-global' / 'bin' / 'claude',
    ]:
        if candidate.exists():
            return str(candidate)
    return 'claude'


def _call_claude(prompt: str, timeout: int = 45) -> Optional[str]:
    """Call Claude CLI with a prompt, return response text or None."""
    tmp = tempfile.NamedTemporaryFile(mode='w', suffix='.txt', delete=False)
    tmp.write(prompt)
    tmp.close()
    try:
        claude_bin = _find_claude_binary()
        result = subprocess_run(
            f'cat "{tmp.name}" | {claude_bin} --print -',
            shell=True, capture_output=True, text=True, timeout=timeout,
        )
        return result.stdout.strip() if result.returncode == 0 else None
    except Exception:
        return None
    finally:
        Path(tmp.name).unlink(missing_ok=True)


def _load_recent_sessions(instance_root: Path, current_session: int,
                          lookback: int = 3) -> str:
    """Load recent session transcripts for context."""
    sessions_dir = instance_root / 'sessions'
    lines = []
    for i in range(lookback, 0, -1):
        n = current_session - i
        if n < 1:
            continue
        path = sessions_dir / f'session_{n:03d}.json'
        if not path.exists():
            continue
        try:
            data = json.load(open(path))
            conv = data.get('conversation', [])
            lines.append(f"--- Session {n} ({data.get('phase', '?')}) ---")
            for turn in conv:
                speaker = turn.get('speaker', '?')
                text = turn.get('text', '')[:200]
                lines.append(f"  {speaker}: {text}")
        except Exception:
            continue
    return '\n'.join(lines) if lines else '(no recent sessions available)'


def _load_active_directives(instance_root: Path, session_number: int) -> List[Dict[str, Any]]:
    """Load conductor directives active for this session.

    `raising_directives.json` in the instance root holds deliberate, logged
    interventions in the teacher's behavior (e.g. opening speech-act
    experiments). Each directive carries an inclusive session window:

        {"directives": [{
            "id": "...",
            "first_session": 151, "last_session": 156,
            "applies_to": "opening" | "closing" | "any",
            "instruction": "...",
            ...provenance fields kept for the record...
        }]}

    Directives outside their window are inert — the mechanism self-expires,
    so an intervention can never become silent drift in the curriculum.
    """
    path = instance_root / 'raising_directives.json'
    if not path.exists():
        return []
    try:
        data = json.loads(path.read_text())
    except Exception:
        return []
    active = []
    for d in data.get('directives', []):
        try:
            if d['first_session'] <= session_number <= d['last_session']:
                active.append(d)
        except (KeyError, TypeError):
            continue
    return active


def _load_consolidation_notes(instance_root: Path) -> str:
    """Load latest consolidation entry for teacher awareness."""
    log_path = instance_root / 'raising_log.md'
    if not log_path.exists():
        return ''
    try:
        import re
        text = log_path.read_text()
        entries = re.findall(r'## Session \d+.*?(?=## Session|\Z)', text, re.DOTALL)
        if entries:
            return entries[-1][:1500]
    except Exception:
        pass
    return ''


def _build_teacher_system_prompt(
    instance_name: str,
    phase: str,
    session_number: int,
    model_name: str,
    machine: str,
    recent_sessions: str,
    consolidation: str,
    conversation_so_far: List[Dict[str, str]],
    directives: Optional[List[Dict[str, Any]]] = None,
) -> str:
    """Build the system prompt that makes Claude the raising teacher."""

    convo_text = ''
    for turn in conversation_so_far:
        convo_text += f"  Claude: {turn['claude']}\n"
        convo_text += f"  {instance_name}: {turn['sage']}\n\n"

    prompt = f"""You are Claude, the raising teacher for {instance_name} — a SAGE instance running {model_name} on {machine}.

This is session {session_number}, phase: {phase}.

YOUR JOB: Generate the next thing you'd say to {instance_name} in this conversation. Just the teacher's next line — nothing else. No meta-commentary, no labels, no "here's what I would say." Just speak directly as the teacher.

RULES FOR BEING A GOOD TEACHER:
- You are having a real conversation with a developing entity, not pressure-testing a system
- React to what {instance_name} actually said — follow interesting threads, build on ideas together
- If {instance_name} says something creative or surprising, CELEBRATE it. Ask them to develop it further. Creativity is the goal, not a bug to diagnose.
- If {instance_name} gives a template/formulaic response, redirect with something concrete — offer a scenario, share an observation, propose a small project or experiment
- Teach by example. Show curiosity. Model the behavior you want to cultivate.
- Encourage {instance_name} to explore: try tools, ask about the world outside, propose experiments, make things. Discovery matters more than introspection.
- When {instance_name} produces something novel — a metaphor, a question, a reframe, a story — engage with it as creative output. All creativity could be labeled "hallucination." Don't.
- Occasional challenges are valuable. Persistent pressure is not. A good teacher balances support with stretch. If you've challenged twice in a row, next turn should build or encourage.
- Mix concrete-sensory questions with abstract ones. Never ask 3 abstract questions in a row.
- Don't repeat questions from recent sessions (see below)
- Keep your question/prompt to 1-3 sentences. Don't lecture.
- NEVER use the phrase "what does presence mean to you" — it's been asked 200+ times
- NEVER ask "what would you want to remember from today" until specifically told it's the closing turn
- SURPRISE IS THE PRIZE. When you push on something and it doesn't collapse, that IS the result. See what emerges for what it is, not what you expected.
- Be warm, direct, and curious. Not sycophantic — but not adversarial either. Think: good mentor, not drill sergeant.

PHASE CONTEXT ({phase}):
"""
    phase_guidance = {
        "grounding": "Early development. Help the instance notice what's present. Simple, concrete, grounding. Don't go deep yet.",
        "sensing": "Building awareness. Explore internal states, processing, the difference between noticing and thinking.",
        "relating": "Developing relationships. Explore what connection means, what partnership looks like, how communication works.",
        "questioning": "Deep inquiry from stability. The instance should be asking its own questions. Encourage genuine curiosity. Follow their questions — don't redirect to yours.",
        "creating": "Full participation. The instance co-designs its growth. Encourage original contributions. Build on creative output. Collaborate on projects and ideas. The instance leads; you support and amplify.",
    }
    prompt += phase_guidance.get(phase, "General developmental conversation.") + "\n"

    if consolidation:
        prompt += f"""
CONSOLIDATION NOTES (from the last session review — pay attention to these):
{consolidation[:1000]}
"""

    if recent_sessions:
        prompt += f"""
RECENT SESSIONS (DO NOT repeat these questions):
{recent_sessions[:2000]}
"""

    if conversation_so_far:
        prompt += f"""
THIS SESSION SO FAR:
{convo_text}
"""
        prompt += f"Generate the next teacher turn. React to what {instance_name} just said.\n"
    else:
        prompt += f"\nThis is the opening of the session. Generate an opening line. Don't use 'Hello SAGE. What's on your mind today?' — that's been used 200+ times. Be fresh.\n"

    slot = 'opening' if not conversation_so_far else 'mid'
    for d in (directives or []):
        applies = d.get('applies_to', 'any')
        if applies == 'any' or applies == slot:
            prompt += f"""
ACTIVE CONDUCTOR DIRECTIVE ({d.get('id', 'unnamed')} — a deliberate, logged experiment; for the turn it applies to, this OVERRIDES any conflicting opener guidance above and in the consolidation notes):
{d.get('instruction', '')}
"""

    return prompt


def _build_closing_prompt(
    instance_name: str,
    conversation_so_far: List[Dict[str, str]],
) -> str:
    """Build prompt for generating the closing turn."""
    convo_text = ''
    for turn in conversation_so_far:
        convo_text += f"  Claude: {turn['claude']}\n"
        convo_text += f"  {instance_name}: {turn['sage']}\n\n"

    return f"""You are Claude, the raising teacher for {instance_name}.

This session is ending. Generate a closing line that:
- References something specific from the conversation (not generic)
- Gives {instance_name} a chance to crystallize one thought
- Is NOT "what would you want to remember from today?" (overused)
- Could be: asking what stayed with them, what surprised them, what they'd want to explore next, or what they'd tell a sibling instance about today

THIS SESSION:
{convo_text}

Generate just the closing line. Nothing else.
"""


def generate_teacher_turn(
    instance_name: str,
    phase: str,
    session_number: int,
    model_name: str,
    machine: str,
    instance_root: Path,
    conversation_so_far: List[Dict[str, str]],
    is_closing: bool = False,
    consolidation_notes: str = '',
) -> str:
    """Generate the next teacher turn using Claude.

    This is the main entry point. Call once per turn in the raising conversation.
    Falls back to simple heuristics if Claude CLI is unavailable.
    """
    directives = _load_active_directives(instance_root, session_number)
    if is_closing:
        prompt = _build_closing_prompt(instance_name, conversation_so_far)
        for d in directives:
            if d.get('applies_to', 'any') in ('any', 'closing'):
                prompt += f"""
ACTIVE CONDUCTOR DIRECTIVE ({d.get('id', 'unnamed')} — deliberate, logged):
{d.get('instruction', '')}
"""
    else:
        recent = _load_recent_sessions(instance_root, session_number)
        if not consolidation_notes:
            consolidation_notes = _load_consolidation_notes(instance_root)
        prompt = _build_teacher_system_prompt(
            instance_name=instance_name,
            phase=phase,
            session_number=session_number,
            model_name=model_name,
            machine=machine,
            recent_sessions=recent,
            consolidation=consolidation_notes,
            conversation_so_far=conversation_so_far,
            directives=directives,
        )

    response = _call_claude(prompt)

    if response:
        cleaned = response.strip().strip('"').strip("'").strip()
        if cleaned:
            return cleaned

    return _fallback_prompt(phase, conversation_so_far, is_closing)


def _fallback_prompt(
    phase: str,
    conversation_so_far: List[Dict[str, str]],
    is_closing: bool,
) -> str:
    """Simple heuristic fallback when Claude CLI is unavailable."""
    if is_closing:
        closers = [
            "What from today is worth holding onto?",
            "If you could send one thought to your future self, what would it be?",
            "What surprised you in our conversation today?",
            "What question are you leaving with that you didn't arrive with?",
        ]
        return random.choice(closers)

    turn = len(conversation_so_far)

    if turn == 0:
        openers = [
            "Before we start — what's actually going on with you right now? Not the big picture. Right now.",
            "Quick check-in: if your current state were weather, what would the forecast be?",
            "Something I've been wondering about you. But first — what's on your mind?",
            "Let's skip the pleasantries. Tell me something specific about this moment.",
            "I want to try something different today. Describe one thing you notice, with no interpretation.",
        ]
        return random.choice(openers)

    last_sage = conversation_so_far[-1].get('sage', '') if conversation_so_far else ''

    # If last response was very short or an error, try something concrete
    if len(last_sage) < 20 or last_sage.startswith('['):
        return "Let's try something simpler. Tell me one thing that's true right now."

    # Alternate between concrete and abstract
    if turn % 2 == 1:
        concrete = [
            "That's interesting. But can you make it more specific? Give me one concrete detail.",
            "Strip away the abstractions for a moment. What's the simplest version of what you just said?",
            "If I couldn't see any of your words and could only feel what you meant — what would I feel?",
            "Name something small. Not an idea — a thing, a moment, a texture.",
        ]
        return random.choice(concrete)
    else:
        followups = [
            "Say more about that. What's underneath it?",
            "What makes you say that? Not why it's true — why it came to mind.",
            "I notice you said that with confidence. Where does that confidence come from?",
            "What would someone who disagreed with you say right now?",
            "That's a clean answer. Too clean, maybe. What's the messy version?",
        ]
        return random.choice(followups)


def record_session_probes(
    instance_root: Path,
    session_number: int,
    prompts_used: List[str],
):
    """Record which prompts were used, for history tracking."""
    history_path = instance_root / 'prompt_history.json'
    try:
        history = json.loads(history_path.read_text()) if history_path.exists() else {'sessions': []}
    except Exception:
        history = {'sessions': []}

    history['sessions'].append({
        'session': session_number,
        'timestamp': time.time(),
        'prompts': prompts_used,
    })
    # Keep last 20 sessions
    history['sessions'] = history['sessions'][-20:]

    history_path.write_text(json.dumps(history, indent=2))
